spring.application.name=backend


spring.datasource.url=jdbc:postgresql://localhost:5432/encrypted_messages
spring.datasource.username=admin
spring.datasource.password=secretpassword


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


encryption.secret.key=VerySecretKeyForAES256!@#$$%^&*12345
jwt.secret=AnotherVerySecretKeyForJWT1234567890